/*=================== 1.*/
/*Output?*/
data ONE;
	input Num Char $;
	if Num = '1';
datalines;
1 23
3 23
1 77
;

proc print data=ONE; 
/*    where Num='1'; */
run; 

/*=================== 2.*/
/*New vars?*/
data work.test; 
	set work.staff (keep = jansales febsales marsales); 
	array diff_sales{3} difsales1 - difsales3; 
	array monthly{3} jansales febsales marsales; 
run;


/*=================== 3.*/

/*You have acquired an existing program from a coworker which uses a macro. It */
/*is not immediately clear to you what this macro is doing. Which OPTION can be */
/*used to put the SAS statements generated by the macro execution into the LOG?*/

/*=================== 4.*/
/*Value of X?*/
data WORK.DATE; 
    X="01Jan1960"d; 
run; 

proc print data=work.date;
run;

/*=================== 5.*/
/*How many raw data records are read during each iteration of the DATA step?*/
data WORK.INFO; 
    infile datalines;
    input  @1 Company $20. @25 State $2. @; 
    if State=' ' then input @30 City Year; 
    input NumEmployees; 
datalines;
Comp1                        CC 12
Comp2                        34 12
Comp3                        12 12
Comp4                        56 12
;
run;

proc print data=work.INFO;
run;

/*=================== 6.*/
/*How can you tell whether you have specified an invalid option in a SAS */
/*program? */

/*	log message indicates an error in a statement that seems to be valid.   */
/*	A log message indicates that an option is not valid or not recognized.   */
/*	The message "PROC running" or "DATA step running" appears at the top of 
    the active window.  */
/*	You can't tell until you view the output from the program.*/

options pageno=-0.5;


/*=================== 7.*/
/*SITE   PATID   DOB         SEXCD   RACECD   TRTMNT */
/*    1      1       11/25/1946    2       1        1 */
/*    1      2       11/01/1972    1       1        2 */
/*    1      3       10/13/1969    2       1        1 */
/*    1      4       05/18/1958    2       1        2 */
/*    1      10      05/24/1999    2       1        1 */
/* */
/*    2      1       03/15/1974    1       2        1 */
/*    2      2       01/04/1983    2       1        2 */
/*    2      3       12/22/1963    1       1        1 */
/*    2      4       12/28/1976    1       9        2 */
/*    2      5       10/04/1958    1       1        1 */
/*    2      10      07/05/1969    1       2        2 */


/*Which selection below would be considered hard-coding? */
/* */
/*   if sexcd eq 1 then sex = "Male" ; else if sexcd eq 2 
     then sex = "Female" ;  0 */
/*   if site eq 1 then sexcd = 2 ; else if site eq 2 then sexcd = 1 ;  1 */
/*   if site eq 1 and sexcd ne 2 then check = 1 ; else if site eq 2 and 
      sexcd ne 1 then check = 2 ;  2 */
/*   birthdt = input(dob, mmddyy10.) ; */




/*=================== 8.*/
/*JOBCATEGORY?*/
data work.staff; 
	JobCategory = 'FA'; 
	JobLevel = '1'; 
	JobCategory2 = JobCategory || JobLevel; 
run;


/*=================== 9.*/
/*How many obs?*/
data work.homework; 
infile datalines; 
input name $ age height; 
if age LE 10; 
/*------10-------20-------30 */
datalines;
John    McCloskey  35  71 
June    Rosesette  10  43 
Tineke  Jones       9  37 
run;



/*=================== 10.*/


proc print data = one; 
run; 
options pageno = 1;
proc means data = one; 
run;
/*Which one of the following OPTIONS statements resets the page number 
to 1 for the second report?*/

/*options pageno = 1;  0 */
/*options pagenum = 1;  1 */
/*options reset pageno = 1;  2 */
/*options reset pagenum = 1; */





/*=================== 11.*/

/*  Table of region by product */
/*  region            product */
/*  Frequency | */
/*  Percent   | */
/*  Row Pct   | */
/*  Col Pct   |     corn        |  cotton  | oranges  |   Total */
/*------------|-----------------|----------|----------| */
/*  EAST      |              2  |      1   |       1  |       4 */
/*            |          22.22  |  11.11   |   11.11  |   44.44 */
/*            |          50.00  |  25.00   |   25.00  | */
/*            |          50.00  |  33.33   |   50.00  | */
/*------------|-----------------|----------|----------| */
/*SOUTH       |              2  |       2  |       1  |       5 */
/*            |          22.22  |   22.22  |   11.11  |   55.56 */
/*            |          40.00  |   40.00  |   20.00  | */
/*            |          50.00  |   66.67  |   50.00  | */
/*------------|-----------------|----------|----------| */
/*  Total                    4          3          2          9 */
/*                       44.44      33.33      22.22     100.00 */

proc freq data = sales; 
   tables region product;  
   tables region * product;  
   tables product * region;  
   tables product; tables region; 
run; 

data sales;
	infile datalines;
	input region $ product $ amt;
datalines;
EAST corn 1.1
EAST corn 2.2
SOUTH cotton 1.6
SOUTH oranges 2.3
; 


/*=================== 12.*/
 
proc format; 
    Value agegrp 
    low-12 ='Pre-Teen' 
    13-high = 'Teen'; 
run; 

/*var Height / nobs min max mean maxdec=1;  0 */
/*   proc means data=SASHELP.CLASS maxdec=1 ;  1 */
/*   proc means data=SASHELP.CLASS min max mean maxdec=1;  2 */
/*   output nobs min max mean maxdec=1;*/

proc means data=SASHELP.CLASS; 
    Var Height; 
    class Sex Age; 
    format Age agegrp.; 
run; 

proc means data=SASHELP.CLASS min max mean maxdec=1;
    Var Height; 
    class Sex Age; 
    format Age agegrp.; 
run; 


/*Analysis Variable : Height N */
/*    Sex   Age        Obs   Minimum   Maximum   Mean */
/*------------------------------------------------------ */
/*    F     Pre-Teen   3     51.3      59.8      55.8 */
/*          Teen       6     56.5      66.5      63.0 */
/*    M     Pre-Teen   4     57.3      64.8      59.7 */
/*          Teen       6     62.5      72.0      66.8*/



